pages:
   before_script:
    - apt update
  script:
    - npm install
    - echo "Deploying to pages"
    - npm run build-storybook
    # - mkdir public
    - mv storybook-static/* public
  artifacts:
    paths:
      - public
  only:
    - master
