pages:
  before_script:
    - apt update
  script:
    - npm install
    - echo "Building storybook..."
    - npm run build-storybook
    - echo "Deploying to pages"
    - mkdir public
    - mv storybook-static/* public
  artifacts:
    paths:
      - public
  only:
    - master
